trigger:
  - master

pool:
  vmImage: 'windows-2019'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'ci'
    workingDir: 'src\BlazingRoller\Client\jslib'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    workingDir: 'src\BlazingRoller\Client\jslib'
    customCommand: 'run build-prod'

- task: PowerShell@2
  displayName: 'Copy Unity artifacts to wwwroot'
  inputs:
    targetType: 'inline'
    script: 'Copy-Item "src\Unity\Baked\*" -Destination "src\BlazingRoller\Server\wwwroot" -recurse'
    failOnStderr: true

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.x SDK'
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore nuget packages'
  inputs:
    command: 'restore'
    projects: 'src\BlazingRoller\Server\BlazingRoller.Server.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build application'
  inputs:
    command: 'build'
    projects: 'src\BlazingRoller\Server\BlazingRoller.Server.csproj'
    arguments: '-c Release -r win-x64'